### ISSUE TITLE
Exported Contract Functions can Collide when Using Other Crates

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-stellar-contract-sdk#244]
In working on an example liquidity pool contract, I am currently depending on the [token contract](https://github.com/stellar/rs-stellar-token-contract) as a normal Cargo dependency

```toml
[dependencies]
# ...
stellar-token-contract = { path = "../rs-stellar-token-contract" }
```

Both contracts contain a `contractimpl` function `initialize`. When building native tests on Mac, these functions seem to suffer a collision at runtime. In other words, calling `liqpool::initialize` inadvertently calls `token::initialize` instead. Changing `liqpool::initialize` to `liqpool::init` resolves this issue.

Ideally, these should either (a) not collide at all or (b) it should be possible to change/disable the exported names when using a dependency.

**Comment by jonjove** [comment]
Full toml for the liquidity pool:

```toml
[package]
name = "stellar-liqpool-contract"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
external = ["stellar-token-contract/external", "dep:ed25519-dalek", "dep:num-bigint", "dep:sha2", "dep:stellar-xdr"]

[dependencies]
ed25519-dalek = { version = "1.0.1", optional = true }
num-bigint = { version = "0.4", optional = true }
sha2 = { version = "0.10.2", optional = true }
stellar-token-contract = { path = "../rs-stellar-token-contract" }
stellar-contract-sdk = { path = "../rs-stellar-contract-sdk/sdk" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "540ed24", features = ["next", "std"], optional = true }

[dev_dependencies]
rand = { version = "0.7.3" }
stellar-liqpool-contract = { path = ".", features = ["external"] }
```
