### ISSUE TITLE
Contract Spec

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-sdk#42]
This description is updated with the resolution:

The design is here: https://github.com/stellar/rs-stellar-contract-sdk/issues/42#issuecomment-1143937788

The list of things to do now are here (https://github.com/stellar/rs-stellar-contract-sdk/issues/42#issuecomment-1146455941):

- [x] stellar/rs-stellar-contract-sdk#114
- [x] stellar/rs-stellar-contract-sdk#115
- [x] stellar/rs-stellar-contract-sdk#116
- [x] https://github.com/stellar/rs-stellar-contract-sdk/issues/24
- [x] stellar/rs-stellar-contract-sdk#117
- [ ] https://github.com/stellar/rs-stellar-contract-sdk/issues/153
- [ ] https://github.com/stellar/rs-stellar-contract-sdk/issues/168
- [ ] stellar/rs-stellar-contract-sdk#118
- [x] stellar/stellar-contract-cli#6
- [ ] stellar/stellar-contract-cli#7
- [ ] stellar/stellar-contract-cli#8
- [ ] https://github.com/stellar/rs-stellar-contract-sdk/issues/142

**Comment by leighmcculloch** [comment]
I looked through these links, and I think we can do the simplest thing for now, which given our alignment and use of Rust is probably a toml file that looks something like:

```toml
[contract]

[[fn]]
symbol = "add32"
args = ["i32", "i32"]
return_type = "i32"

[[fn]]
symbol = "add64"
args = ["i64", "i64"]
return_type = "i64"

[[fn]]
symbol = "hndmsg"
args = ["obj:binary"]
return_type = "bool"
```

The above example provides the fields as specified in [CAP-47](https://stellar.org/protocol/cap-47) (@sisuresh).

The example assumes that types can be referenced using the `SCValType` definition in CAP-47, here expressed in an abbreviated form but otherwise consistent.
